### ISSUE TITLE
Support Themes

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/showcase#68]
It would be helpful to be able to include classes on the samples or other places that will bring in the theme from the app.  Particularly useful with custom themes.

**Comment by kaspth** [comment]
@olbrich hey! Sorry, this one slipped through the cracks for me.

We've tried to keep Showcase's surrounding UI light on CSS rules since it's for every Rails app and not just Bullet Train ones.

If you're visiting /docs/showcase in your Bullet Train app, and clicking on the built-in previews, it should be using your Bullet Train theme. So I'm confused, can you say a little more about what you're looking for? Thanks!

**Comment by olbrich** [comment]
@kaspth I think when I first set up showcase on my BT app, the BT themes did not work and I had to eject a template and modify it for those to work.  If that's correct, it's probably more of a problem with the BT implementation of showcase than showcase itself.  

Although maybe what I meant was to suggest a configuration option that would allow developers to add arbitrary classes to the 'body' or 'main' elements of the layout.

I was probably doing some dark-mode work at the time, so this may be a moot point now.

**Comment by kaspth** [comment]
> I think when I first set up showcase on my BT app, the BT themes did not work and I had to eject a template and modify it for those to work. If that's correct, it's probably more of a problem with the BT implementation of showcase than showcase itself.

Ah ok, yeah, I haven't heard about that before. I'll keep a look out.

> Although maybe what I meant was to suggest a configuration option that would allow developers to add arbitrary classes to the 'body' or 'main' elements of the layout.

We could potentially do that, sure. I'm curious, do you know what you'd like to add to body/main? I don't know what the use case is.

**Comment by jagthedrummer** [comment]
@kaspth In my app when I go to `/docs/showcase` it's showing me everything in the default blue theme, even though my app uses the `emerald` theme.

I see this by default:
![CleanShot 2023-08-03 at 13 47 29](https://github.com/bullet-train-co/showcase/assets/58702/6889daf4-87e2-4ada-bb02-ae5f0cb4c4e0)

On non-showcase pages the opening `html` tag has `class="theme-emerald"` on it.

```
<html class="theme-emerald">
 ...
</html>
```

If I go into the inspector in showcase and manually add that class to the opening `html` tag, then it starts using the correct theme:
![CleanShot 2023-08-03 at 13 48 38](https://github.com/bullet-train-co/showcase/assets/58702/287f3190-a9c1-451c-b7fc-7a8b061c1491)

I set the theme in `config/initializers/theme.rb` by doing this:

```
BulletTrain::Themes::Light.color = :emerald
```

So maybe we just need some way of injecting that config option into the `html` tag inside showcase.

**Comment by kaspth** [comment]
Ahhh I see! I had no idea the theming required an attribute on the HTML tag. I'll come up with something to fix this.

**Comment by olbrich** [comment]
@jagthedrummer Yeah, that's exactly it.  Thanks for helping us figure that out, I'd lost track of what I had to edit to make it work.

**Comment by kaspth** [comment]
I just found out we have a hosted version of Showcase with all of Bullet Train's partials in there. I can see how it would be really cool to have a theme switcher on here! https://bullettrain.co/docs/showcase/previews/tailwind/components/button

I'm gonna be looking into that.

**Comment by kaspth** [comment]
I'm trying out the theme picker version over here https://github.com/bullet-train-co/bullet_train-core/pull/377

Just realized we can inject the current theme colors in a much simpler way though, so I can do that first.

**Comment by kaspth** [comment]
Ok, doing that over in https://github.com/bullet-train-co/bullet_train-core/pull/378

**Comment by kaspth** [comment]
Ok, this should be rolling out in the next version of `bullet_train-themes-light`, and then the `color` and `secondary_color` are used properly on the Showcase side like @jagthedrummer showed above. Thanks @olbrich @jagthedrummer!
