### ISSUE TITLE
Add Address Field to showcase

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/showcase#76]
The showcase here... https://bullettrain.co/docs/showcase is super helpful, but it does not currently include the new `address_field`.

**Comment by pascallaliberte** [comment]
Noted 👍

**Comment by pascallaliberte** [comment]
I've added a note in Issue https://github.com/bullet-train-co/bullet_train-core/issues/533, that's the repo in which we'll be documenting the field in Bullet Train's `light` theme's showcase previews.
